
package ec.edu.ups.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-01-20T20:14:06.125-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class ClienteSOAP_ClienteSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://Service.ups.edu.ec/", "ClienteSOAPService");

    private ClienteSOAP_ClienteSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClienteSOAPService ss = new ClienteSOAPService(wsdlURL, SERVICE_NAME);
        ClienteSOAP port = ss.getClienteSOAPPort();  
        
        {
        System.out.println("Invoking insertarCredito...");
        ec.edu.ups.service.Credito _insertarCredito_arg0 = null;
        port.insertarCredito(_insertarCredito_arg0);


        }

        System.exit(0);
    }

}
